# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: assistant.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'assistant.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x61ssistant.proto\x12\tassistant\"#\n\x0cVoiceRequest\x12\x13\n\x0b\x61udio_chunk\x18\x01 \x01(\x0c\";\n\rVoiceResponse\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x0c\n\x04lang\x18\x02 \x01(\t\x12\x0e\n\x06\x61\x63tion\x18\x03 \x01(\t2S\n\x0eVoiceAssistant\x12\x41\n\x08\x43onverse\x12\x17.assistant.VoiceRequest\x1a\x18.assistant.VoiceResponse(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'assistant_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_VOICEREQUEST']._serialized_start=30
  _globals['_VOICEREQUEST']._serialized_end=65
  _globals['_VOICERESPONSE']._serialized_start=67
  _globals['_VOICERESPONSE']._serialized_end=126
  _globals['_VOICEASSISTANT']._serialized_start=128
  _globals['_VOICEASSISTANT']._serialized_end=211
# @@protoc_insertion_point(module_scope)
